// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACBQuTH_IUe_Qj1YKXf4LH_IiwdOnNvIo',
    appId: '1:539340628104:web:7a74df74daf0693e8fbf3d',
    messagingSenderId: '539340628104',
    projectId: 'ulabeventpedia-b3836',
    authDomain: 'ulabeventpedia-b3836.firebaseapp.com',
    storageBucket: 'ulabeventpedia-b3836.appspot.com',
    measurementId: 'G-SZKCBX2VLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTIeQG1LrsqFZAKVu6jmqfSkZRpoMfK6U',
    appId: '1:539340628104:android:a4ffdf08578676268fbf3d',
    messagingSenderId: '539340628104',
    projectId: 'ulabeventpedia-b3836',
    storageBucket: 'ulabeventpedia-b3836.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiC9L7CE17hTE-wE2bWMA0dLnesz-1o4c',
    appId: '1:539340628104:ios:8cb27d35738bc2d58fbf3d',
    messagingSenderId: '539340628104',
    projectId: 'ulabeventpedia-b3836',
    storageBucket: 'ulabeventpedia-b3836.appspot.com',
    iosBundleId: 'com.example.ulabEventpediaMain',
  );
}
